name: CI/CD Pipeline

# This workflow will be triggered when changes are pushed to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  # Test job to run your tests
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # or any Node version you're using

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test --if-present  # This will run your test script

  # Deployment job to Vercel (triggered only if tests pass)
  deploy:
    needs: test  # This job will run after the 'test' job successfully completes
    runs-on: ubuntu-latest
    if: success()  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}  # Store your Vercel token in GitHub Secrets
        run: |
            echo "HELLOWORLD"
            echo "Y" | vercel --prod --token $VERCEL_TOKEN
